### ISSUE TITLE
Where to place custom reset callback wrapper class?

### ISSUE THREAD

**Issue by aadharna** [Bam4d/Griddly#112]
So, I took a first pass at the custom reset environment. Where in Griddly would you like this placed? I was thinking: `python/griddly/util/rllib/environment/custom_reset_callback_wrapper.py` or `python/griddly/util/wrappers/custom_reset_callback_wrapper.py`

Also, at first I was thinking that we might want to override your custom `GymWrapper` class. I went back and forth a few times before deciding on `gym.Wrapper`. Do you have an opinion on that? 

```python
import gym


class SetLevelWithCallback(gym.Wrapper):
    """GymWrapper to set the level with a callback function in Griddly.

    The callback_fn should output a string representation of the level.
    """

    def __init__(self, env, callback_fn):
        super(SetLevelWithCallback, self).__init__(env=env)
        self.create_level_fn = callback_fn

    def reset(self, **kwargs):
        level_string = self.create_level_fn()
        assert(isinstance(level_string, str))
        kwargs['level_string'] = level_string
        return self.env.reset(**kwargs)

    def step(self, action):
        return self.env.step(action)


if __name__ == "__main__":
    import gym
    from griddly import GymWrapperFactory
    from griddly import gd

    game = 'zelda_partially_observable'

    fpath = f'./src/Griddly/resources/games/Single-Player/GVGAI/{game}.yaml'

    wrapper = GymWrapperFactory()

    wrapper.build_gym_from_yaml(
        'Zelda-Adv',
        fpath,
        level=1,
        global_observer_type=gd.ObserverType.SPRITE_2D,
        player_observer_type=gd.ObserverType.BLOCK_2D
    )

    env = gym.make("GDY-Zelda-Adv-v0")
    s = env.reset()
    f = lambda: """wwwwwwwwwwwww
w....+++.+g.w
w.+.w+g.+...w
w...++Ag+.3.w
w+..+...+...w
w....w+++...w
w.........g.w
w.3...+++.+ww
wwwwwwwwwwwww"""

    env = SetLevelWithCallback(env, f)
    _ = env.reset()
    env.render(observer='global')
    import time
    time.sleep(2)
    env.close()
```

**Comment by Bam4d** [comment]
Hi @aadharna Thanks for the question.

I think the best place for this would be in `python/griddly/util/wrappers/custom_reset_callback_wrapper.py` Its definitely a nice way of wrapping a simple level generator, and its not tied to rllib so no need to put it in the rllib package. 

There's also a new RLLib compatible LevelGenerator class in one of my latest branches which does things a bit more "ray like" so you can pass tune parameters to the level generator, or even diffferent level generators as hyperparams.. 

Looks something like this:
```
'env_config': {
    'invalid_action_masking': True,
    'generate_valid_action_trees': True,
    'level_generator': {
        'class': ClustersLevelGenerator,
        'config': {
            'width': 6,
            'height': 6,
            'p_red': 0.7,
            'p_green': 0.7,
            'p_blue': 0.7,
            'm_red': 4,
            'm_blue': 4,
            'm_green': 4,
            'm_spike': 4,
        }
    },
    'yaml_file': gdy_file,
     .....
```

And the super class is a simple interface which you can do whatever you want with the impl. (use a NN, scripted generator etc).
```
class LevelGenerator:

    def __init__(self, config):
        self._config = config

    def generate(self):
        raise NotImplementedError()
```

**Comment by Bam4d** [comment]
Here's the branch with the changes for the above stuff: https://github.com/Bam4d/Griddly/commit/bc81674bf6539f8e593af53238eeeaa0cdaad544

**Comment by aadharna** [comment]
So, this is actually an interesting interface question. I've been using the `ray.remote` decorator directly in my code and therefore it looks like our usages of ray differ. In my code right now, I have a base class for my level generators that (for the generation of levels) follows the convention that I lifted from how people normally setup vectorized gym envs (which I'm open to changing): 

```python
import abc

class BaseGenerator(abc.ABC):
    def __init__(self):
        super(BaseGenerator, self).__init__()
        pass

    def step(self, **kwargs):
        """This is mutation in a population-based setup; but also would be the step in a gradient-based setup"""
        raise NotImplementedError

    def update_from_lvl_string(self, level_string):
        raise NotImplementedError

    def generate_fn_wrapper(self):
        def _generate() -> str:
            raise NotImplementedError
        return _generate

    def __str__(self):
        """This function is necessary for our generators. This function will take whatever
        the internal representation of our "levels" are and turn it into a string that we
        can then use to set the simulator to in Griddly.

        :return:
        """
        raise NotImplementedError
```

This was so that when I do a call such as: 

```python
    def optimize(self) -> list:
        """
        Optimize each NN-pair on its PAIRED environment
        :return: list of future-refs to the new optimized weights
        """
        refs = [optimize_agent_on_env.remote(trainer_constructor=self.registrar.trainer_constr, #e.g. PPOTrainer
                                             trainer_config=self.registrar.trainer_config, #e.g. PPOTrainer.config
                                             registered_gym_name=self.registrar.name,
                                             level_string_monad=p.generator.generate_fn_wrapper(),
                                             actor_critic_weights=p.solver.state_dict(),
                                             pair_id=p.id)
                for p in self.pairs]
        return refs
```

so that I can query the function in the worker thread. And then in the worker thread, I run `trainer_config['env_config']['level_string'] = level_string_monad()`. This method works for setting the env once at the start of the training cycle. And therefore, to generalize this, I used the above class but passed the `generator.generate_fn_wrapper()` call as the callback. 

This seems fairly different than what you put in the RLlibEnv code above where you're instantiating an entire generator class inside the RLlibEnv. I would think you would want the generator and environment decoupled to allow for more modularity. Is there a reason you baked the generator directly into the env?

**Comment by Bam4d** [comment]
There's no *correct* way to do any of this. In your example, passing `generate_fn_wrapper` as the parameter will either copy the entire base class state onto the remote as well, *or* call the monad using RPC introducing latency in the round-trip (not sure how `ray.remote` deals with this internally). So there's no *real* difference in instantiating in on the worker individually vs instantiating once and then copying to the remotes.

If however the instantiation/production of the generator is complicated/requires GPU you might want to run it in multiple threads so instantiating on the workers is better.

There's probably reasons for doing it both ways depending on the use case. Stick with whatever way works for you.
