### ISSUE TITLE
Issue Running on HPC

### ISSUE THREAD

**Issue by amykhoover** [Bam4d/Griddly#113]
**Issue**
My team and I have incorporated Griddly in our research and I would like to run some code on our HPC (Redhat cluster). Question: Can I sidestep Griddly's Vulkan dependency if I am running it headless?

Installing Griddly "as is" produces the following error: 

Traceback (most recent call last):
File "mypython.py", line 22, in <module>
    import griddly
  File "/path/myvenv/lib/python3.7/site-packages/griddly/__init__.py", line 16, in <module>
    gd = importlib.import_module('python_griddly')
  File "/afs/cad/linux/anaconda3.7/anaconda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libvulkan.so.1: cannot open shared object file: No such file or directory

Thank you!

**Comment by Bam4d** [comment]
Hi Amy thanks for the question.

Make sure you are setting both the `player_observer_type` and `global_observer_type` to `VECTOR` i.e:

```
env = gym.make(
  'GDY-MyEnvironmentName-v0',
  player_observer_type=gd.ObserverType.VECTOR,
  global_observer_type=gd.ObserverType.VECTOR,
  ...
)
```

If this doesn't work then you might have to ask to get vulkan installed on your cluster. Vulkan is a standard library used for rendering, so hopefully whoever maintains the HPC cluster would be happy to add it.

I'll have a think about how to possibly stop Vulkan getting loaded if its not needed in the mean time. Thanks!

**Comment by amykhoover** [comment]
Thanks so much :)
