### ISSUE TITLE
No way to install on Apple Silicon (M1)?

### ISSUE THREAD

**Issue by Akhilez** [Bam4d/Griddly#118]
Hi!

I switched to Apple silicon M1 macbook from intel macbook and I'm no longer able to install griddly.

I'm using python 3.8 and miniconda 4.10.0

```
(dl) btak@akhil-mac-air python % pip install griddly
ERROR: Could not find a version that satisfies the requirement griddly (from versions: none)
ERROR: No matching distribution found for griddly
```

I cloned the repo (master), went to python dir and ran `python setup.py install`. The package was installed, but I get the following error when I run my env:
```
Traceback (most recent call last):
  File "/Users/btak/code/reward_lab/rl_talk/env_demo_sokoban.py", line 2, in <module>
    from griddly import gd
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dl/lib/python3.8/site-packages/griddly-1.2.1-py3.8-macosx-11.0-arm64.egg/griddly/__init__.py", line 16, in <module>
    gd = importlib.import_module('python_griddly')
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dl/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'python_griddly'
```

It is in this line:
```
# Load the binary
gd = importlib.import_module('python_griddly')
```

From the lines above that line, it looks like maybe I'm missing 'libs' and 'Debug' folders? I checked and I didn't find those dirs.
```
# The python libs are found in the current directory
module_path = os.path.dirname(os.path.realpath(__file__))
libs_path = os.path.join(module_path, 'libs')

sys.path.extend([libs_path])

debug_path = os.path.join(module_path, '../../Debug/bin')
sys.path.extend([debug_path])
```

It's possible that I'm in a completely wrong path. Please help

**Comment by Bam4d** [comment]
Hi, I've not tried this on M1 silicon before so I dont know if this is going to be compatible.

Either way, you'll need to build the C++ libraries first before doing the python install. (the instructions are on the README).

Let me know how it goes!

**Comment by Akhilez** [comment]
Worked! Thanks! <3
