### ISSUE TITLE
Segmentation fault when both observers as NONE

### ISSUE THREAD

**Issue by bwitherspoon** [Bam4d/Griddly#124]
The following produces a segmentation fault. Ideally it would produce a warning. Using latest version available with pip (1.2.6).

```py
env = gym.make(
    "GDY-Clusters-v0",
    player_observer_type=gd.ObserverType.NONE,
    global_observer_type=gd.ObserverType.NONE
)
```

```sh
Segmentation fault (core dumped)
```

OS:
- Linux
- Fedora 34

**Comment by Bam4d** [comment]
There's actually no reason for `gd.ObserverType.NONE` to exist, so I just removed it. Setting to NONE has the same effect as just not rendering observations anyway.
