### ISSUE TITLE
[FEATURE]: Using objects attributes as a reward

### ISSUE THREAD

**Issue by Mo-youssef** [Bam4d/Griddly#128]
It will be cool to be able to use object attributes such as count, as a reward.
For example:
In Clusters environment, the reward is proportional to the number of in-place boxes. i.e. to define the reward as
 `- reward: blue_block:count`

**Comment by Bam4d** [comment]
Thinking about this more.... the `:count` property is more of a legacy convenience than anything thats important in the way Griddly works. Counters can be easily implemented using custom variables, `incr` and `decr` etc.

Encouraging `:count` would be encouraging an edge case that is outside the **normal** way of doing things.
