### ISSUE TITLE
Observations of dead agents

### ISSUE THREAD

**Issue by samvelyan** [Bam4d/Griddly#178]
**Describe the bug**
Dead agents receiving non-zero observations.

**To Reproduce**
1. Open any multi-agent environment
2. observe the observations of agents that are dead

**Expected behavior**
I think it is common for dead agents to receives all zeros as observations.

**Additional context**
- Also, restricting the action-space of dead agents to only no-op is common!

**Comment by Bam4d** [comment]
when you say "restricting the action space" do you mean the action masking should only allow no-ops?

**Comment by samvelyan** [comment]
Yes, this is an approach we took in SMAC, but I'm not sure if this is something you have to worry about on the Griddly side. The environment designer could just write a wrapper for this.

**Comment by Bam4d** [comment]
closed by #194
