### ISSUE TITLE
Compliance with Gym API

### ISSUE THREAD

**Issue by Markus28** [Bam4d/Griddly#196]
It seems like `GymWrapper` does not fully comply with the 0.22.0 Gym API (which is what is stated in requirements.txt). 
There were lots of subtle changes in the Gym API that people probably don't immediately notice.

Some issues I noticed:

### Seeding
- Usually, when `None` is passed as a seed, some (unreproducible) source of entropy is used for seeding. In `GymWrapper`, a constant seed is used. This can lead to problems for people who just call `env.seed()`, expecting to get a randomized environment.
- `env.seed` should return a list of seeds that were used. Currently, `None` is returned
- `GymWrapper.seed` also seeds the action/observation spaces. This is usually not done in Gym and may lead to problems for people who first seed the action spaces, then the entire environment. Imho, this isn't a big issue and I would actually argue that this is the preferable approach, but it's not what Gym does
- We usually seed an environment **before** we reset it. When you use the example from https://griddly.readthedocs.io/en/latest/getting-started/gym/index.html and call `env.seed()`, we get an exception.
- These issues are somewhat secondary because the seed method is being deprecated, see the next point

### Reset
- Reset should accept the keyword argument `seed`. If it is **not** `None`, the environment will be seeded and then reset. If it is `None` but the environment *has never been seeded before*, some source of entropy will be used to seed the environment anyways.
- In the new API, we should be able to pass the keyword argument `return_info` to `env.reset`. If this is true, a tuple (obs, info) should be returned. Otherwise, just the observation.

### Metadata
- A new format for the render-related metadata was introduced. The metadata should contain the keys "render_modes" and "render_fps". "render.modes" should be removed.

### Rendering
I honestly can't say much about this because I'm not certain I completely understand the implementation in this repository yet.
- It looks like the render-mode is fixed to some degree during initialization (ASCII vs pixels (?)), is that right? There is an upcoming API change in Gym that will also use this approach so this is not a big issue. However, one might want to start using the format that will be assumed by Gym (a single `render_mode` keyword iirc).
- In human-rendering, environments usually return a boolean, not a numpy array
- The metadata is currently suggesting that human-rendering and rgb_array-rendering are available. However, it seems like ASCII representations is also supported. Is that true? That's also a valid way to render environments but the metadata should be adjusted accordingly.

These are mostly non-breaking changes. The only exception may be the seeding stuff :/

Once these issues are sorted out, the API compliance can be checked via the `check_env` function from `gym.utils.env_checker` :)

**Comment by Bam4d** [comment]
Superceded by #282
