### ISSUE TITLE
GriddlyJS: Tab in GDY editor goes 4 spaces

### ISSUE THREAD

**Issue by cool-RR** [Bam4d/Griddly#256]
When I use tab (or shift-tab) in the GDY editor, it goes 4 spaces right or left. All the YAML examples are indented to 2 spaces. You should pick one and stick with it. I recommend 2 spaces but 4 will also be okay.

**Comment by Bam4d** [comment]
Think this should be fixed now :)

**Comment by cool-RR** [comment]
Confirmed, it's fixed.
