### ISSUE TITLE
GriddlyJS: Background tile not working 

### ISSUE THREAD

**Issue by cool-RR** [Bam4d/Griddly#257]
See attached screenshot: 

![screenshot_TURING_2022-11-09_230055](https://user-images.githubusercontent.com/56778/200940912-b513b610-e0c5-4317-98fc-8e5b08e7be21.jpg)

I've defined a background sprite, pressed Ctrl-S (and even refreshed) but it doesn't show.

GDY file: https://gist.github.com/cool-RR/398e429c72e5682d935fbe42f5d644b2

**Comment by Bam4d** [comment]
So background tiling needs to be in the `Observers` part of the configuration

```
Environment:
  Name: Coffee
  Description: Blah
  Player:
    AvatarObject: robot
  Observers:
    Sprite2D:
      TileSize: 24
      BackgroundTile: gvgai/newset/floor2.png
```
