### ISSUE TITLE
cannot import name 'ImageEncoder' from 'gym.wrappers.monitoring.video_recorder'

### ISSUE THREAD

**Issue by SimonOuellette35** [Bam4d/Griddly#280]
I installed griddly using pip, and then ran the following code:

```
import gym
import griddly
from griddly import gd

if __name__ == '__main__':

    env = gym.make(
        'GDY-Sokoban-v0',
        player_observer_type=gd.ObserverType.VECTOR,
        global_observer_type=gd.ObserverType.SPRITE_2D,
        level=0,
        max_steps=None,
    )
    env.reset()

    # Replace with your own control algorithm!
    for s in range(1000):
        action = int(input("Enter action ==> "))
        obs, reward, done, info = env.step(action)
        env.render(observer='global') # Renders the entire environment

        if done:
            env.reset()

```
Aside from quite a few warnings not pasted here, the main error I'm getting is the following trace:

Traceback (most recent call last):
  File "/manualSokoban.py", line 20, in <module>
    env.render(observer='global') # Renders the entire environment
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/gym/wrappers/order_enforcing.py", line 51, in render
    return self.env.render(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/gym/wrappers/env_checker.py", line 53, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/gym/utils/passive_env_checker.py", line 316, in env_render_passive_checker
    result = env.render(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/griddly/GymWrapper.py", line 469, in render
    from griddly.RenderTools import RenderWindow
  File "/lib/python3.11/site-packages/griddly/RenderTools.py", line 2, in <module>
    from gym.wrappers.monitoring.video_recorder import ImageEncoder
ImportError: cannot import name 'ImageEncoder' from 'gym.wrappers.monitoring.video_recorder' (/lib/python3.11/site-packages/gym/wrappers/monitoring/video_recorder.py)

Looking at my conda list, I have the following gym package installed: gym                       0.26.2                   pypi_0    pypi
I'm using Ubuntu.

I'm guessing I don't have the right gym version?

**Comment by Bam4d** [comment]
Hi.

At the moment, the version of gym required I think is 0.22. We're currently upgrading to gymnasium in #282 which should be merged soon.
