### ISSUE TITLE
State access

### ISSUE THREAD

**Issue by ocorcoll** [Bam4d/Griddly#78]
Thanks for creating this tool and its environments, they look great! I was wondering if you are planning to provide access to the state of the game. Some sort of "observer" where, for example, rows are objects and columns are their attributes (x,y, type, etc). If not, what would be the easiest way to access this information right now? I'm guessing the Vector observer gives this information partially.

**Comment by Bam4d** [comment]
Hi @ocorcoll.

So what you are after is kind of semantic observer? 

The vector observer gives back a tensor of size `C,H,W` where each value is a `0` or a `1`. the `C` dimension refers to the object type so if there is a `1` it means that that object is present. (so this gives you your (x,y,type).

You mention (x, y, type, `etc`). What are you referring to here in terms of `etc`? What other information would you want to be returned?

Additionally. there is an option `env.enable_history(True)` (i think this is not documented anywhere). This opeion will stream back a list of "events" that are happening in the environment in the `info` returned from the `env.step` method. This semantic information might be useful to you also.

**Comment by ocorcoll** [comment]
Thanks for the quick response. 

By etc I meant attributes like "opened/closed" in case of doors, the agent is carrying the key or not. I believe this is not needed for the present environments (when a door opens the episode finishes?) and I could infer if the key has been picked. But I can imagine objects having state like lights (on/off) or boxes (opened/closed). 

As you say, for now I can infer (x,y) from the vector binary map and just reverse engineer the type for each game. I'll take a look at the enable_history flag.

**Comment by Bam4d** [comment]
OK I understand. Yes this seems like a good addition. Thanks!

**Comment by Bam4d** [comment]
AB#103

**Comment by ocorcoll** [comment]
Thanks for doing this change. A caveat on the implementation is when an entity has special attributes (like the direction of the agent in the Spiders env), these are not passed as state. Right now only the name of the entity and its location are passed as state. It would be great to handle these cases which will, I believe, become more common.

**Comment by Bam4d** [comment]
@ocorcoll makes lots of sense, I will add this. #99

**Comment by Bam4d** [comment]
@ocorcoll this is now in version `0.3.2`
